// <auto-generated />
using CoreCrudRelationalDb.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreCrudRelationalDb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreCrudRelationalDb.Models.Entities.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("CoreCrudRelationalDb.Models.Entities.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departmanlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Muhasebe"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Bilgi İşlem"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Pazarlama"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "İnsan Kaynakları"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Planlama ve Üretim"
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Lojistik"
                        },
                        new
                        {
                            Id = 7,
                            Ad = "İdari"
                        });
                });

            modelBuilder.Entity("CoreCrudRelationalDb.Models.Entities.Calisan", b =>
                {
                    b.HasOne("CoreCrudRelationalDb.Models.Entities.Departman", "Departman")
                        .WithMany("Calisanlar")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("CoreCrudRelationalDb.Models.Entities.Departman", b =>
                {
                    b.Navigation("Calisanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
